--inserting the values in the violations tables

insert into violation values(1, "RECKLESS/DANGEROUS DRIVING TWO WHEELER", 1000.00);
insert into violation values(2, "OVER SPEEDING", 2000.00);
insert into violation values(3, "REF. GO FOR HIRE", 500);
insert into violation values(4, "DEM. EXCESS FARE", 500);
insert into violation values(5, "DEF. SILENCER", 500);
insert into violation values(6, "SHRILL HORN", 500);
insert into violation values(7, "WRONG PARKING", 1000);
insert into violation values(8, "WITHOUT D.L TWO WHEELERS", 1000);
insert into violation values(9, "JUMPING TRAFFIC SIGNNALS", 500);
insert into violation values(10, "CUTT. YELLOW LINE", 500);
insert into violation values(11, "LANE DISCIPLINE", 500);
insert into violation values(12, "OVERTAKING FROM LEFT", 500);
insert into violation values(13, "DEF. REG NO PLATE", 500);
insert into violation values(14, "WITHOUT UNIFORM", 500);
insert into violation values(15, "WITHOUT INSURANCE", 2000);
insert into violation values(16, "USING HIGH BEAM LIGHT", 500);
insert into violation values(17, "DEF. HEADLIGHT", 500);
insert into violation values(18, "DEF. TAILLIGHT", 500);
insert into violation values(19, "BALDTYRES", 500);
insert into violation values(20, "FOOT BOARD TRAVEL", 500);
insert into violation values(21, "USING MOBILE PHONE", 1000);
insert into violation values(22, "NOT WEARING SEAT BELT", 500);
insert into violation values(23, "CARRYING LENGTH MATERIAL", 500);
insert into violation values(24, "CARR. EXCESS SCHOOL CHILDREN", 200);
insert into violation values(25, "TRIPPLE RIDING", 500);
insert into violation values(26, "NO ENTRY", 500);
insert into violation values(27, "ZIG ZAG DRIVING", 500);
insert into violation values(28, "PARKED AT INTERSECTION", 1000);
insert into violation values(29, "RIDING ON THE FOOTPATH", 500);
insert into violation values(30, "RIDING WITHOUT HELMET", 500);
insert into violation values(31, "HTV PROHIBITED", 500);
insert into violation values(32, "DID NOT PRODUCE DOCUMENTS", 500);
insert into violation values(33, "WITHOUT NUMBER PLATE", 500);
insert into violation values(34, "CARRYING PASSENGER ON TOP", 500);
insert into violation values(35, "CARRYING EXTRA PASSENGER", 500);
insert into violation values(36, "CARRYING EXTRA PASSENGER -BUS/TRANSPORT", 200);
insert into violation values(37, "DRIVING WHEN MENTALLY/PHYSICALLY UNFIT TO DRIVE", 1000);
insert into violation values(38, "CARRYING MORE THAN 5 PASSENGERS IN HTV", 200);
insert into violation values(39, "CARRYING MORE THAN 2 PERSON IN LMV", 200);
insert into violation values(40, "MISBEHAVIOR WITH THE POLICE OFFICER", 2000);
insert into violation values(41, "RECKLESS/DANGEROUS DRIVING -TRANSPORT", 1000);
insert into violation values(42, "MINOR DRIVING", 5000);
insert into violation values(43, "DRIVING DURING DISQULIFICATION", 10000);
insert into violation values(44, "RACKING AND TRIAL OF SPEED", 5000);
insert into violation values(45, "DISOBEDIENCE/ OBSTRUCTION/ REFUSAL/ FALSE INFORMATION", 1000);
insert into violation values(46, "RECKLESS/ DANGEROUS DRIVING -NON TRANSPORT", 1000);
insert into violation values(47, "RECKLESS/ DANGEROUS DRIVING AUTO", 1000);
insert into violation values(48, "AIR/NOISE POLLUTION 2/3 WHEELER", 1000);
insert into violation values(49, "AIR/NOISE POLLUTION -4 WHEELER", 1000);
insert into violation values(50, "AIR/NOISE POLLUTION HTV/ CARRIAGE", 1000);
insert into violation values(51, "OBSTRUCTING TRAFFIC", 500);
insert into violation values(52, "REFUSE TO STOP AT POLICE SIGNAL", 500);
insert into violation values(53, "CHASE AND CAUGHT", 500);
insert into violation values(54, "U TURN PROHIBITED", 500);
insert into violation values(55, "FREE WHEEELING", 5000);
insert into violation values(56, "OWNER TO BE PROSECUTED", 5000);
insert into violation values(57, "PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS", 1000);
insert into violation values(58, "PARKING OPP. TO ANOTHER PARKED VEHICLE", 1000);
insert into violation values(59, "DOUBLE PARKING", 1000);
insert into violation values(60, "STOPPING ON WHITE/STOP LINE", 1000);
insert into violation values(61, "PARKING NEAR BUS STOP/ SCHOOL/ HOSPITAL ETC", 1000);
insert into violation values(62, "PARKING ON FOOTPATH", 1000);
insert into violation values(63, "PARKING NEAR ROAD CROSSING OR BENDTOP OF HILL ETC", 1000);
insert into violation values(64, "CARRYING EXTRA PASSENGER IN AUTO", 200);
insert into violation values(65, "NO PARKING", 1000);
insert into violation values(66, "CROSSING MEDIAN LINE AND GOING AGAINST FLOW OF TRAFFIC", 500);
insert into violation values(67, "AGAINST ONE WAY", 500);
insert into violation values(68, "USE OF BLACK FILM/ OTHER MATERAILS", 500);
insert into violation values(69, "BUSES STOP ANYWHERE BUT BUS STOPS AND RESPECTIVE DEPOTS", 500);
insert into violation values(70, "NOT WEARING HELMOT -PILLION RIDER", 500);
insert into violation values(71, "WITHOUT INSURANCE TWO WHEELERS", 1000);
insert into violation values(72, "WITHOUT INSURANCE LMV", 2000);
insert into violation values(73, "WITHOUT INSURANCE LGV AND OTHERS", 4000);
insert into violation values(74, "USE OF HORN AT PROHIBITED PLACES 2/ 3 WHEELERS", 500);
insert into violation values(75, "USE OF HORN AT PROHIBITED PLACES 4 WHEELERS", 1000);
insert into violation values(76, "OVER SPEEDING 2W/ 3 WHEELERS AND LMV", 1000);
insert into violation values(77, "OVER SPEEDING  LGV/HGV AND OTHERS", 2000);
insert into violation values(78, "OWNER TO BE PROSECUTED 2/ 3 WHEELERS", 1000);
insert into violation values(79, "OWNER TO BE PROSECUTED LMBV", 2000);
insert into violation values(80, "OWNER TO BE PROSECUTED HGV/ OTHERS", 5000);
insert into violation values(81, "WITHOUT D.L THREE WHEELERS", 1000);
insert into violation values(82, "WITHOUT D.L LMV", 2000);
insert into violation values(83, "WITHOUT D.L OTHERS", 5000);
insert into violation values(84, "WITHOUT INSURANCE THREE WHEELERS", 1000);
insert into violation values(85, "RIGHT TURN PROHIBITED", 500);
insert into violation values(86, "DRUNK AND DRIVE",NULL);
insert into violation values(87, "AUTO/ CAB/ TAXI/ DISPLAY CARD", NULL);
insert into violation values(88, "JAY WALKING", NULL);
insert into violation values(89, "WITHOUT PERMIT/ VIOLATION OF PERMIT", NULL);
insert into violation values(90, "WITHOUT EMISSION CERTIFICATE", NULL);
insert into violation values(91, "VEHICLE WITHOUT REGISTRATION", NULL);
insert into violation values(92, "ALTERATION OF VEHICLE", NULL);
insert into violation values(93, "WITHOUT CERTIFICATE OF FITNESS", NULL);

--periodic select statement trial run 
select * from violation;